name: DeepSeek Code Review

on:
  push:
    branches:
      - main

# Permissões necessárias para comentar no PR
permissions:
  pull-requests: write
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest
    name: Code Review

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List changed files
        run: git diff --name-only HEAD~1 HEAD

      - name: DeepSeek Code Review
        uses: hustcer/deepseek-review@v1
        with:
          # Token da API DeepSeek (configure nas secrets do repositório)
          chat-token: ${{ secrets.CHAT_TOKEN }}

          # Modelo a ser usado (opcional)
          model: "deepseek-chat"

          # Padrões de arquivos para incluir na revisão
          include-patterns: "TestFile.java,*.properties,*.sh,*.gradle,pom.xml"

          # Padrões de arquivos para excluir da revisão
          exclude-patterns: ""

          # Temperatura para geração de respostas (0-2)
          temperature: 1.0

          # Comprimento máximo do conteúdo para revisão (0 = sem limite)
          max-length: 0

          # Prompt personalizado para o sistema
          sys-prompt: |
            Você é um revisor de código especializado em Java, arquivos de configuração e scripts Shell.
            Por favor, analise o código considerando:
            1. Boas práticas de programação Java
            2. Possíveis problemas de segurança
            3. Problemas de performance
            4. Qualidade e clareza do código
            5. Conformidade com padrões de código
            6. Configurações adequadas em arquivos properties
            7. Boas práticas em scripts shell
            Forneça feedback construtivo e sugestões específicas de melhorias.

          # Prompt do usuário
          user-prompt: |
            Por favor, revise as seguintes alterações de código, 
            focando em qualidade, segurança e boas práticas:

          # Token do GitHub (opcional, usa o padrão se não especificado)
          github-token: ${{ github.token }}

      # Opcional: Adicionar um passo para notificação em caso de falha
      - name: Notify on Failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ A revisão de código automática falhou. Por favor, verifique os logs da action para mais detalhes.'
            })
